---
title: "Home"
author: "aiden"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Howdy

My name is Aiden loe and I am a psychometrician at the University of Cambridge.

I completed my undergraduate joint degree in psychology/business at the University of Glasgow. 

I pursued my Masters (social and development psychology) and PhD (psychometrics) at the University of Cambridge. 

My PhD supervisor was Professor John Rust. 

I like to keep things simple and neat. 

That makes learning easier. 

Here we cover basic R and stats for our workshop. 
 
But I also add things that I pick up along the way. 


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-98916204-1', 'auto');
  ga('send', 'pageview');

</script>